In [2]:
import re
import pandas as pd

In [3]:
f= open("chat.txt",'r',encoding='utf-8')

In [4]:
data=f.read()

In [5]:
print(data)

18/01/21, 15:05 - Akanksha "Team"
19/01/21, 15:05 - You were added
27/08/22, 14:56 - Monika  Hope you candidates are ready to attend *Electric Vehicle Workshop*

🔜 you will receive meeting link 🔗

⚜️ *Topic* - Back EMF & it's significance in Re-Generative Braking System
⏰ *11AM*
🗓️ *28th August 2022*
27/08/22, 16:28 - Shweta: <Media omitted>

27/08/22, 17:46 - Aknasha: <Media omitted>
27/08/22, 17:46 - Ayushi: hello all
27/08/22, 17:51 - Ashwani : 🫣🤭
27/08/22, 18:07 - Monika : https://forms.gle/dNBpdL5NMsHmhF9k7
27/08/22, 18:07 - Monika : Swati

Register wala form
27/08/22, 18:09 - Swati : Thankyou

27/08/22, 20:46 - Aayushi : 🔥 *Founder's Opinion | Student should be upskilled for Electric Vehicle Industry*
➖➖➖➖➖
🤔💭 Our industry leader
➖➖➖➖➖
💢 *Click Here to watch*
https://www.youtube.com/watch?v=23fQ9-XUSCU
➖➖➖➖➖
💢 *Click Here to watch full Interview Session*
https://www.youtube.com/watch?v=iBIcCGpSpeM&t=574s
➖➖➖➖➖
💢 To take part in *28 August 2022* Free workshop of  and clear your query and doubts, kindly fill this form here 👇🏻👇🏻
https://tinyurl.com/24vee9jt

27/08/22, 23:06 - Sameera : 😊 Sukriya!!
28/08/22, 08:40 - Bhaviya : <Media omitted>

28/08/22, 08:50 - Monika : Hn sir
28/08/22, 08:54 - Shweta : Okay
28/08/22, 10:31 - Ayushi : 🔥 *Free Live Workshop  Design and Development*
Watch Live Streaming Now only on YouTube:- https://youtu.be/ZWlyGYWw7Cw

To take part in our next Free workshop of *Electric Vehicle Design and Development* and clear your query and doubts, kindly fill the below form so that we can provide you the useful information. 👇🏻👇🏻
https://forms.gle/Ux6YWQkjMAkhvthR6

For More details Kindly Join our *Electric Vehicle* Alert *WhatsApp* Group from the below link 👇🏻
https://chat.whatsapp.com/D4VpUnfyafU0dS2Hp3vjuJ
28/08/22, 10:44 - Monika : This message was deleted
28/08/22, 10:45 - Aayushi : Attendance Sheet | 28th AUGUST 2022 | Electric Vehicle Design & Development Live Free Workshop
https://forms.gle/Ux6YWQkjMAkhvthR6


For More details Kindly Join our Alert *WhatsApp* Group from the below link 👇🏻
https://chat.whatsapp.com/D4VpUnfyafU0dS2Hp3vjuJ
28/08/22, 11:20 - Bhavika : Matlab okay?

28/08/22, 12:26 - Monika  : This message was deleted
28/08/22, 12:42 - Monika : Thank you for attending today's session. Hope you liked it , your doubts regarding career in EV Industry is cleared.
➖➖➖➖➖➖
For attending upcoming sessions fill the form👇🏻👇🏻

https://forms.gle/Ux6YWQkjMAkhvthR6
28/08/22, 12:44 - Monika : Thank you for attending today's Workshop. Hope you liked the workshop.
➖➖➖➖➖➖
For attending upcoming sessions, fill the form👇🏻👇🏻

https://forms.gle/Ux6YWQkjMAkhvthR6

28/08/22, 17:23 - Shweta : <Media omitted>
28/08/22, 17:23 - Swatika : <Media omitted>
28/08/22, 17:23 - Swatika : <Media omitted>
28/08/22, 17:23 - Swatika : <Media omitted>
28/08/22, 17:23 - Swatika : <Media omitted>
28/08/22, 17:23 - Swatika : <Media omitted>
28/08/22, 17:23 - Swatika : <Media omitted>
28/08/22, 17:23 - Swatika : <Media omitted>
28/08/22, 17:23 - Swatika : <Media omitted>
28/08/22, 17:23 - Swatika : <Media omitted>
28/08/22, 17:23 - Swatika : <Media omitted>
28/08/22, 17:23 - Swatika : I am joining class
28/08/22, 17:23 - Swatika : <Media omitted>
28/08/22, 17:23 - Swatika : <Media omitted>
28/08/22, 17:23 - Swatika : <Media omitted>
28/08/22, 17:23 - Swatika : <Media omitted>
28/08/22, 19:57 - Ayushi : <Media omitted>
28/08/22, 19:57 - Ayuka : <Media omitted>
28/08/22, 19:57 - Ayuka : <Media omitted>
28/08/22, 19:57 - Ayuka : <Media omitted>
28/08/22, 19:57 - Ayush : <Media omitted>
28/08/22, 19:57 - Ayuka : <Media omitted>
28/08/22, 19:57 - Ayuka : <Media omitted>
28/08/22, 19:57 - Ayuka : <Media omitted>
28/08/22, 23:43 - Monika : 😍😍yeeee
28/08/22, 23:44 - Ayushi : <Media omitted>

30/08/22, 15:39 - Ayushi : <Media omitted>
30/08/22, 15:41 - Ashish: <Media omitted>
30/08/22, 15:41 - Ashish : <Media omitted>
30/08/22, 15:41 - Ashish : <Media omitted>
30/08/22, 15:41 - Ashish : <Media omitted>
30/08/22, 15:41 - Ashish : <Media omitted>
30/08/22, 15:41 - Ashish : <Media omitted>
30/08/22, 15:42 - Ashish : <Media omitted>
30/08/22, 15:42 - Ashish : <Media omitted>
30/08/22, 15:42 - Ashish : <Media omitted>

30/08/22, 16:33 - Bhaviya: Syllabus

30/08/22, 19:04 - Bhaviya: 👍🏻
30/08/22, 19:04 - Ashish : 👌🏻
30/08/22, 19:04 - Bhaviya: 👌🏻

In [6]:
pattern= '\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s'

In [7]:
messages=re.split(pattern,data)[1:]

In [8]:
messages

['Akanksha "Team"\n',
 'You were added\n',
 "Monika  Hope you candidates are ready to attend *Electric Vehicle Workshop* \n\n🔜 you will receive meeting link 🔗\n\n⚜️ *Topic* - Back EMF & it's significance in Re-Generative Braking System\n⏰ *11AM*\n🗓️ *28th August 2022*\n",
 'Shweta: <Media omitted>\n\n',
 'Aknasha: <Media omitted>\n',
 'Ayushi: hello all\n',
 'Ashwani : 🫣🤭\n',
 'Monika : https://forms.gle/dNBpdL5NMsHmhF9k7\n',
 'Monika : Swati\n\nRegister wala form\n',
 'Swati : Thankyou \n\n',
 "Aayushi : 🔥 *Founder's Opinion | Student should be upskilled for Electric Vehicle Industry*\n➖➖➖➖➖\n🤔💭 Our industry leader\n➖➖➖➖➖\n💢 *Click Here to watch* \nhttps://www.youtube.com/watch?v=23fQ9-XUSCU\n➖➖➖➖➖\n💢 *Click Here to watch full Interview Session* \nhttps://www.youtube.com/watch?v=iBIcCGpSpeM&t=574s\n➖➖➖➖➖\n💢 To take part in *28 August 2022* Free workshop of  and clear your query and doubts, kindly fill this form here 👇🏻👇🏻\nhttps://tinyurl.com/24vee9jt\n\n",
 'Sameera : 😊 Sukriya!!\n',
 'Bhaviya : <Media omitted>\n\n',
 'Monika : Hn sir\n',
 'Shweta : Okay\n',
 'Ayushi : 🔥 *Free Live Workshop  Design and Development* \nWatch Live Streaming Now only on YouTube:- https://youtu.be/ZWlyGYWw7Cw\n\nTo take part in our next Free workshop of *Electric Vehicle Design and Development* and clear your query and doubts, kindly fill the below form so that we can provide you the useful information. 👇🏻👇🏻\nhttps://forms.gle/Ux6YWQkjMAkhvthR6\n\nFor More details Kindly Join our *Electric Vehicle* Alert *WhatsApp* Group from the below link 👇🏻\nhttps://chat.whatsapp.com/D4VpUnfyafU0dS2Hp3vjuJ\n',
 'Monika : This message was deleted\n',
 'Aayushi : Attendance Sheet | 28th AUGUST 2022 | Electric Vehicle Design & Development Live Free Workshop \nhttps://forms.gle/Ux6YWQkjMAkhvthR6\n\n\nFor More details Kindly Join our Alert *WhatsApp* Group from the below link 👇🏻\nhttps://chat.whatsapp.com/D4VpUnfyafU0dS2Hp3vjuJ\n',
 'Bhavika : Matlab okay?\n\n',
 'Monika  : This message was deleted\n',
 "Monika : Thank you for attending today's session. Hope you liked it , your doubts regarding career in EV Industry is cleared. \n➖➖➖➖➖➖\nFor attending upcoming sessions fill the form👇🏻👇🏻\n\nhttps://forms.gle/Ux6YWQkjMAkhvthR6\n",
 "Monika : Thank you for attending today's Workshop. Hope you liked the workshop. \n➖➖➖➖➖➖\nFor attending upcoming sessions, fill the form👇🏻👇🏻\n\nhttps://forms.gle/Ux6YWQkjMAkhvthR6\n\n",
 'Shweta : <Media omitted>\n',
 'Swatika : <Media omitted>\n',
 'Swatika : <Media omitted>\n',
 'Swatika : <Media omitted>\n',
 'Swatika : <Media omitted>\n',
 'Swatika : <Media omitted>\n',
 'Swatika : <Media omitted>\n',
 'Swatika : <Media omitted>\n',
 'Swatika : <Media omitted>\n',
 'Swatika : <Media omitted>\n',
 'Swatika : <Media omitted>\n',
 'Swatika : I am joining class\n',
 'Swatika : <Media omitted>\n',
 'Swatika : <Media omitted>\n',
 'Swatika : <Media omitted>\n',
 'Swatika : <Media omitted>\n',
 'Ayushi : <Media omitted>\n',
 'Ayuka : <Media omitted>\n',
 'Ayuka : <Media omitted>\n',
 'Ayuka : <Media omitted>\n',
 'Ayush : <Media omitted>\n',
 'Ayuka : <Media omitted>\n',
 'Ayuka : <Media omitted>\n',
 'Ayuka : <Media omitted>\n',
 'Monika : 😍😍yeeee\n',
 'Ayushi : <Media omitted>\n\n',
 'Ayushi : <Media omitted>\n',
 'Ashish: <Media omitted>\n',
 'Ashish : <Media omitted>\n',
 'Ashish : <Media omitted>\n',
 'Ashish : <Media omitted>\n',
 'Ashish : <Media omitted>\n',
 'Ashish : <Media omitted>\n',
 'Ashish : <Media omitted>\n',
 'Ashish : <Media omitted>\n',
 'Ashish : <Media omitted>\n\n',
 'Bhaviya: Syllabus \n\n',
 'Bhaviya: 👍🏻\n',
 'Ashish : 👌🏻\n',
 'Bhaviya: 👌🏻']

In [9]:
dates=re.findall(pattern,data)

In [10]:
dates

['18/01/21, 15:05 - ',
 '19/01/21, 15:05 - ',
 '27/08/22, 14:56 - ',
 '27/08/22, 16:28 - ',
 '27/08/22, 17:46 - ',
 '27/08/22, 17:46 - ',
 '27/08/22, 17:51 - ',
 '27/08/22, 18:07 - ',
 '27/08/22, 18:07 - ',
 '27/08/22, 18:09 - ',
 '27/08/22, 20:46 - ',
 '27/08/22, 23:06 - ',
 '28/08/22, 08:40 - ',
 '28/08/22, 08:50 - ',
 '28/08/22, 08:54 - ',
 '28/08/22, 10:31 - ',
 '28/08/22, 10:44 - ',
 '28/08/22, 10:45 - ',
 '28/08/22, 11:20 - ',
 '28/08/22, 12:26 - ',
 '28/08/22, 12:42 - ',
 '28/08/22, 12:44 - ',
 '28/08/22, 17:23 - ',
 '28/08/22, 17:23 - ',
 '28/08/22, 17:23 - ',
 '28/08/22, 17:23 - ',
 '28/08/22, 17:23 - ',
 '28/08/22, 17:23 - ',
 '28/08/22, 17:23 - ',
 '28/08/22, 17:23 - ',
 '28/08/22, 17:23 - ',
 '28/08/22, 17:23 - ',
 '28/08/22, 17:23 - ',
 '28/08/22, 17:23 - ',
 '28/08/22, 17:23 - ',
 '28/08/22, 17:23 - ',
 '28/08/22, 17:23 - ',
 '28/08/22, 17:23 - ',
 '28/08/22, 19:57 - ',
 '28/08/22, 19:57 - ',
 '28/08/22, 19:57 - ',
 '28/08/22, 19:57 - ',
 '28/08/22, 19:57 - ',
 '28/08/22, 19:57 - ',
 '28/08/22, 19:57 - ',
 '28/08/22, 19:57 - ',
 '28/08/22, 23:43 - ',
 '28/08/22, 23:44 - ',
 '30/08/22, 15:39 - ',
 '30/08/22, 15:41 - ',
 '30/08/22, 15:41 - ',
 '30/08/22, 15:41 - ',
 '30/08/22, 15:41 - ',
 '30/08/22, 15:41 - ',
 '30/08/22, 15:41 - ',
 '30/08/22, 15:42 - ',
 '30/08/22, 15:42 - ',
 '30/08/22, 15:42 - ',
 '30/08/22, 16:33 - ',
 '30/08/22, 19:04 - ',
 '30/08/22, 19:04 - ',
 '30/08/22, 19:04 - ']

In [11]:
df=pd.DataFrame({"user_message":messages,"message_date":dates})

In [12]:
df

                                         user_message        message_date
0                                   Akanksha "Team"\n  18/01/21, 15:05 -
1                                    You were added\n  19/01/21, 15:05 -
2   Monika  Hope you candidates are ready to atten...  27/08/22, 14:56 -
3                         Shweta: <Media omitted>\n\n  27/08/22, 16:28 -
4                          Aknasha: <Media omitted>\n  27/08/22, 17:46 -
..                                                ...                 ...
57                       Ashish : <Media omitted>\n\n  30/08/22, 15:42 -
58                             Bhaviya: Syllabus \n\n  30/08/22, 16:33 -
59                                      Bhaviya: 👍🏻\n  30/08/22, 19:04 -
60                                      Ashish : 👌🏻\n  30/08/22, 19:04 -
61                                        Bhaviya: 👌🏻  30/08/22, 19:04 -

[62 rows x 2 columns]

In [13]:
df["message_date"]=pd.to_datetime(df['message_date'], format="%d/%m/%y, %H:%M - ")

In [14]:
df

                                         user_message        message_date
0                                   Akanksha "Team"\n 2021-01-18 15:05:00
1                                    You were added\n 2021-01-19 15:05:00
2   Monika  Hope you candidates are ready to atten... 2022-08-27 14:56:00
3                         Shweta: <Media omitted>\n\n 2022-08-27 16:28:00
4                          Aknasha: <Media omitted>\n 2022-08-27 17:46:00
..                                                ...                 ...
57                       Ashish : <Media omitted>\n\n 2022-08-30 15:42:00
58                             Bhaviya: Syllabus \n\n 2022-08-30 16:33:00
59                                      Bhaviya: 👍🏻\n 2022-08-30 19:04:00
60                                      Ashish : 👌🏻\n 2022-08-30 19:04:00
61                                        Bhaviya: 👌🏻 2022-08-30 19:04:00

[62 rows x 2 columns]

In [15]:
df["message_date"]

0    2021-01-18 15:05:00
1    2021-01-19 15:05:00
2    2022-08-27 14:56:00
3    2022-08-27 16:28:00
4    2022-08-27 17:46:00
             ...
57   2022-08-30 15:42:00
58   2022-08-30 16:33:00
59   2022-08-30 19:04:00
60   2022-08-30 19:04:00
61   2022-08-30 19:04:00
Name: message_date, Length: 62, dtype: datetime64[ns]

In [16]:
df.shape

(62, 2)

In [17]:
df.rename(columns={'message_date':'date'},inplace=True)

In [18]:
df

                                         user_message                date
0                                   Akanksha "Team"\n 2021-01-18 15:05:00
1                                    You were added\n 2021-01-19 15:05:00
2   Monika  Hope you candidates are ready to atten... 2022-08-27 14:56:00
3                         Shweta: <Media omitted>\n\n 2022-08-27 16:28:00
4                          Aknasha: <Media omitted>\n 2022-08-27 17:46:00
..                                                ...                 ...
57                       Ashish : <Media omitted>\n\n 2022-08-30 15:42:00
58                             Bhaviya: Syllabus \n\n 2022-08-30 16:33:00
59                                      Bhaviya: 👍🏻\n 2022-08-30 19:04:00
60                                      Ashish : 👌🏻\n 2022-08-30 19:04:00
61                                        Bhaviya: 👌🏻 2022-08-30 19:04:00

[62 rows x 2 columns]

In [19]:
users= []
messages = []

for message in df['user_message']:
    entry = re.split('([\w\W]+?):\s',message)
    if entry[1:]:
        users.append(entry[1])
        messages.append(" ".join(entry[2:]))
    else:
            users.append('group notification')
            messages.append(entry[0])
df['user']=users
df['message']=messages
df.drop(columns=['user_message'], inplace = True)

In [20]:
df

,date,user,message
0,2021-01-18 15:05:00,group notification,"Akanksha ""Team""\n"
1,2021-01-19 15:05:00,group notification,You were added\n
2,2022-08-27 14:56:00,group notification,Monika Hope you candidates are ready to atten...
3,2022-08-27 16:28:00,Shweta,<Media omitted>\n\n
4,2022-08-27 17:46:00,Aknasha,<Media omitted>\n
...,...,...,...
57,2022-08-30 15:42:00,Ashish,<Media omitted>\n\n
58,2022-08-30 16:33:00,Bhaviya,Syllabus \n\n
59,2022-08-30 19:04:00,Bhaviya,👍🏻\n
60,2022-08-30 19:04:00,Ashish,👌🏻\n
61,2022-08-30 19:04:00,Bhaviya,👌🏻

In [21]:
df

,date,user,message
0,2021-01-18 15:05:00,group notification,"Akanksha ""Team""\n"
1,2021-01-19 15:05:00,group notification,You were added\n
2,2022-08-27 14:56:00,group notification,Monika Hope you candidates are ready to atten...
3,2022-08-27 16:28:00,Shweta,<Media omitted>\n\n
4,2022-08-27 17:46:00,Aknasha,<Media omitted>\n
...,...,...,...
57,2022-08-30 15:42:00,Ashish,<Media omitted>\n\n
58,2022-08-30 16:33:00,Bhaviya,Syllabus \n\n
59,2022-08-30 19:04:00,Bhaviya,👍🏻\n
60,2022-08-30 19:04:00,Ashish,👌🏻\n
61,2022-08-30 19:04:00,Bhaviya,👌🏻

In [22]:
df['year']=df['date'].dt.year

In [23]:
df

,date,user,message,year
0,2021-01-18 15:05:00,group notification,"Akanksha ""Team""\n",2021
1,2021-01-19 15:05:00,group notification,You were added\n,2021
2,2022-08-27 14:56:00,group notification,Monika Hope you candidates are ready to atten...,2022
3,2022-08-27 16:28:00,Shweta,<Media omitted>\n\n,2022
4,2022-08-27 17:46:00,Aknasha,<Media omitted>\n,2022
...,...,...,...,...
57,2022-08-30 15:42:00,Ashish,<Media omitted>\n\n,2022
58,2022-08-30 16:33:00,Bhaviya,Syllabus \n\n,2022
59,2022-08-30 19:04:00,Bhaviya,👍🏻\n,2022
60,2022-08-30 19:04:00,Ashish,👌🏻\n,2022
61,2022-08-30 19:04:00,Bhaviya,👌🏻,2022

In [24]:
df['month']=df['date'].dt.month_name()

In [25]:
df

,date,user,message,year,month
0,2021-01-18 15:05:00,group notification,"Akanksha ""Team""\n",2021,January
1,2021-01-19 15:05:00,group notification,You were added\n,2021,January
2,2022-08-27 14:56:00,group notification,Monika Hope you candidates are ready to atten...,2022,August
3,2022-08-27 16:28:00,Shweta,<Media omitted>\n\n,2022,August
4,2022-08-27 17:46:00,Aknasha,<Media omitted>\n,2022,August
...,...,...,...,...,...
57,2022-08-30 15:42:00,Ashish,<Media omitted>\n\n,2022,August
58,2022-08-30 16:33:00,Bhaviya,Syllabus \n\n,2022,August
59,2022-08-30 19:04:00,Bhaviya,👍🏻\n,2022,August
60,2022-08-30 19:04:00,Ashish,👌🏻\n,2022,August
61,2022-08-30 19:04:00,Bhaviya,👌🏻,2022,August

In [26]:
df['day']=df['date'].dt.day

In [27]:
df

,date,user,message,year,month,day
0,2021-01-18 15:05:00,group notification,"Akanksha ""Team""\n",2021,January,18
1,2021-01-19 15:05:00,group notification,You were added\n,2021,January,19
2,2022-08-27 14:56:00,group notification,Monika Hope you candidates are ready to atten...,2022,August,27
3,2022-08-27 16:28:00,Shweta,<Media omitted>\n\n,2022,August,27
4,2022-08-27 17:46:00,Aknasha,<Media omitted>\n,2022,August,27
...,...,...,...,...,...,...
57,2022-08-30 15:42:00,Ashish,<Media omitted>\n\n,2022,August,30
58,2022-08-30 16:33:00,Bhaviya,Syllabus \n\n,2022,August,30
59,2022-08-30 19:04:00,Bhaviya,👍🏻\n,2022,August,30
60,2022-08-30 19:04:00,Ashish,👌🏻\n,2022,August,30
61,2022-08-30 19:04:00,Bhaviya,👌🏻,2022,August,30

In [28]:
df['hour']=df['date'].dt.hour

In [29]:
df

,date,user,message,year,month,day,hour
0,2021-01-18 15:05:00,group notification,"Akanksha ""Team""\n",2021,January,18,15
1,2021-01-19 15:05:00,group notification,You were added\n,2021,January,19,15
2,2022-08-27 14:56:00,group notification,Monika Hope you candidates are ready to atten...,2022,August,27,14
3,2022-08-27 16:28:00,Shweta,<Media omitted>\n\n,2022,August,27,16
4,2022-08-27 17:46:00,Aknasha,<Media omitted>\n,2022,August,27,17
...,...,...,...,...,...,...,...
57,2022-08-30 15:42:00,Ashish,<Media omitted>\n\n,2022,August,30,15
58,2022-08-30 16:33:00,Bhaviya,Syllabus \n\n,2022,August,30,16
59,2022-08-30 19:04:00,Bhaviya,👍🏻\n,2022,August,30,19
60,2022-08-30 19:04:00,Ashish,👌🏻\n,2022,August,30,19
61,2022-08-30 19:04:00,Bhaviya,👌🏻,2022,August,30,19

In [30]:
df['minute']=df['date'].dt.minute

In [31]:
df

,date,user,message,year,month,day,hour,minute
0,2021-01-18 15:05:00,group notification,"Akanksha ""Team""\n",2021,January,18,15,5
1,2021-01-19 15:05:00,group notification,You were added\n,2021,January,19,15,5
2,2022-08-27 14:56:00,group notification,Monika Hope you candidates are ready to atten...,2022,August,27,14,56
3,2022-08-27 16:28:00,Shweta,<Media omitted>\n\n,2022,August,27,16,28
4,2022-08-27 17:46:00,Aknasha,<Media omitted>\n,2022,August,27,17,46
...,...,...,...,...,...,...,...,...
57,2022-08-30 15:42:00,Ashish,<Media omitted>\n\n,2022,August,30,15,42
58,2022-08-30 16:33:00,Bhaviya,Syllabus \n\n,2022,August,30,16,33
59,2022-08-30 19:04:00,Bhaviya,👍🏻\n,2022,August,30,19,4
60,2022-08-30 19:04:00,Ashish,👌🏻\n,2022,August,30,19,4
61,2022-08-30 19:04:00,Bhaviya,👌🏻,2022,August,30,19,4